"""Task a09 checks: deterministic synthetic fixtures and declared expectations.

Every fixture is regenerated from committed code and compared against the hash
recorded in research/g4/a09/fixture-registry.json. The historical G2 reference
is additionally compared against the hash quoted in the G2 evidence record and,
when present, byte for byte against the committed artifact.

No native APIs, no iTunes, no COM, no UI. Generated bytes are written only to
pytest temporary directories, never into the repository.
"""

from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import struct
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
A09_DIR = REPO_ROOT / "research" / "g4" / "a09"
REGISTRY_PATH = A09_DIR / "fixture-registry.json"
EXPECTATIONS_DIR = A09_DIR / "expectations"


def _load_module(module_name, path):
    spec = importlib.util.spec_from_file_location(module_name, path)
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolve their owning module through sys.modules, so register
    # before executing or @dataclass fails under postponed annotations.
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


fixtures = _load_module("a09_fixtures", A09_DIR / "fixtures.py")
manifests = _load_module("a09_manifest", A09_DIR / "manifest.py")

REGISTRY = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
ROWS = {row["fixture_id"]: row for row in REGISTRY["fixtures"]}
ALL_IDS = [row["fixture_id"] for row in REGISTRY["fixtures"]]
SILENCE_ID = "ITL-G4-A09-PCM-48000-MONO-0010-SILENCE"
ODD_ID = "ITL-G4-A09-PCM-48000-MONO-1500-INFO-ODD"


# ---------------------------------------------------------------------------
# Registry and reference reproduction
# ---------------------------------------------------------------------------
def test_registry_is_current_for_this_generator():
    assert REGISTRY["schema"] == fixtures.REGISTRY_SCHEMA
    assert REGISTRY["generator"] == fixtures.GENERATOR_PATH
    current = fixtures.sha256_file(A09_DIR / "fixtures.py")
    assert REGISTRY["generator_sha256"] == current, (
        "fixture-registry.json is stale, regenerate it with "
        "python3 research/g4/a09/fixtures.py --write-registry research/g4/a09/fixture-registry.json"
    )
    assert sorted(ALL_IDS) == sorted(spec.fixture_id for spec in fixtures.SPECS)


def test_reference_regeneration_matches_quoted_record():
    quoted = fixtures.REFERENCE_QUOTED
    data = fixtures.build_fixture(fixtures.spec_by_id(fixtures.REFERENCE_ID))
    assert len(data) == quoted["bytes"]
    assert hashlib.sha256(data).hexdigest() == quoted["sha256"]
    assert hashlib.sha256(fixtures.data_payload(data)).hexdigest() == quoted["pcm_sha256"]


def test_reference_regeneration_is_byte_identical_to_committed_artifact():
    artifact = REPO_ROOT / fixtures.REFERENCE_ARTIFACT
    if not artifact.exists():
        pytest.skip("reference artifact is not present in this checkout")
    data = fixtures.build_fixture(fixtures.spec_by_id(fixtures.REFERENCE_ID))
    assert artifact.read_bytes() == data


@pytest.mark.parametrize("fixture_id", ALL_IDS)
def test_fixture_regeneration_matches_recorded_hash(fixture_id):
    row = ROWS[fixture_id]
    data = fixtures.build_fixture(fixtures.spec_by_id(fixture_id))
    assert len(data) == row["size_bytes"]
    assert hashlib.sha256(data).hexdigest() == row["sha256"]
    assert hashlib.sha256(fixtures.data_payload(data)).hexdigest() == row["pcm_sha256"]


@pytest.mark.parametrize("fixture_id", ALL_IDS)
def test_fixture_regeneration_is_deterministic(fixture_id):
    spec = fixtures.spec_by_id(fixture_id)
    assert fixtures.build_fixture(spec) == fixtures.build_fixture(spec)


# ---------------------------------------------------------------------------
# Container and sample level structure
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("fixture_id", ALL_IDS)
def test_riff_structure_matches_declared_layout(fixture_id):
    row = ROWS[fixture_id]
    spec = fixtures.spec_by_id(fixture_id)
    data = fixtures.build_fixture(spec)
    chunks = fixtures.chunk_map(data)
    assert chunks == row["chunks"]
    ids = [chunk["id"] for chunk in chunks]
    assert ids[0] == "fmt "
    assert ids.count("data") == 1
    fmt_chunk = chunks[0]
    audio_format, channels, rate, byte_rate, block_align, bits = struct.unpack_from(
        "<HHIIHH", data, fmt_chunk["payload_offset"]
    )
    assert audio_format == 1
    assert channels == spec.channels == row["channels"]
    assert rate == spec.sample_rate_hz == row["sample_rate_hz"]
    assert bits == spec.bits_per_sample == row["bits_per_sample"]
    assert block_align == channels * bits // 8
    assert byte_rate == rate * block_align
    payload = fixtures.data_payload(data)
    assert len(payload) == spec.frames * block_align
    data_chunk = [chunk for chunk in chunks if chunk["id"] == "data"][0]
    if spec.metadata_shape == "none":
        assert ids == ["fmt ", "data"]
        assert data_chunk["payload_offset"] == 44, "canonical 44 byte header expected"
    if spec.metadata_placement == "before_data":
        assert data_chunk["payload_offset"] != 44, "metadata before data must shift the audio"


@pytest.mark.parametrize("fixture_id", ALL_IDS)
def test_samples_stay_in_range_and_match_recorded_stats(fixture_id):
    row = ROWS[fixture_id]
    data = fixtures.build_fixture(fixtures.spec_by_id(fixture_id))
    payload = fixtures.data_payload(data)
    values = struct.unpack("<%dh" % (len(payload) // 2), payload)
    assert min(values) >= -32768
    assert max(values) <= 32767
    assert fixtures.pcm_stats(payload) == row["pcm"]


def test_family_covers_the_declared_variation_matrix():
    rates = {row["sample_rate_hz"] for row in REGISTRY["fixtures"]}
    channels = {row["channels"] for row in REGISTRY["fixtures"]}
    durations = {row["duration_ms"] for row in REGISTRY["fixtures"]}
    shapes = {row["metadata_shape"] for row in REGISTRY["fixtures"]}
    assert {8000, 22050, 44100, 48000} <= rates
    assert {1, 2} <= channels
    assert len(durations) >= 4
    assert {"none", "riff-info-ascii", "riff-info-odd", "id3v23-unicode"} <= shapes
    assert ROWS[SILENCE_ID]["pcm"]["peak_abs"] == 0
    assert all(row["pcm"]["peak_abs"] <= 32767 for row in REGISTRY["fixtures"])


def test_family_exercises_riff_pad_bytes():
    subchunk_pads = 0
    for fixture_id in ALL_IDS:
        data = fixtures.build_fixture(fixtures.spec_by_id(fixture_id))
        for chunk in fixtures.chunk_map(data):
            subchunk_pads += sum(sub["pad_bytes"] for sub in chunk.get("subchunks", []))
    assert subchunk_pads >= 1, "no fixture exercises RIFF pad bytes"
    odd_lists = [chunk for chunk in ROWS[ODD_ID]["chunks"] if chunk["id"] == "LIST"]
    assert odd_lists, "the odd length fixture must carry a LIST chunk"
    assert any(sub["pad_bytes"] == 1 for sub in odd_lists[0]["subchunks"])


def test_stereo_channels_are_distinguishable():
    spec = fixtures.spec_by_id("ITL-G4-A09-PCM-48000-STEREO-1500")
    payload = fixtures.data_payload(fixtures.build_fixture(spec))
    values = struct.unpack("<%dh" % (len(payload) // 2), payload)
    left = values[0::2]
    right = values[1::2]
    assert len(left) == len(right) == spec.frames
    assert left != right, "a stereo fixture whose channels match cannot show channel order"


# ---------------------------------------------------------------------------
# Materialisation rules
# ---------------------------------------------------------------------------
def test_written_fixture_carries_the_declared_mtime(tmp_path):
    spec = fixtures.spec_by_id(SILENCE_ID)
    path = fixtures.write_fixture(tmp_path, spec, fixtures.build_fixture(spec))
    assert path.stat().st_mtime_ns == spec.mtime_ns
    assert hashlib.sha256(path.read_bytes()).hexdigest() == ROWS[SILENCE_ID]["sha256"]


def test_generator_refuses_to_materialise_inside_the_repository():
    spec = fixtures.spec_by_id(SILENCE_ID)
    with pytest.raises(SystemExit):
        fixtures.write_fixture(A09_DIR / "unwanted-binaries", spec, b"")
    assert not (A09_DIR / "unwanted-binaries").exists()


# ---------------------------------------------------------------------------
# Declared expectation manifests
# ---------------------------------------------------------------------------
def _complete_declaration(kind="native_import_discovery", fixture_ids=None):
    chosen = list(fixture_ids) if fixture_ids else ALL_IDS[:3]
    manifest = manifests.build_template(
        REGISTRY,
        candidate_id="A09-SELFTEST-0001",
        candidate_kind=kind,
        fixture_ids=chosen,
        playlist_name="A09 Self Test Order",
    )
    manifest["declaration_state"] = "declared"
    manifest["preflight"] = {
        "a08_review_id": "a08-review-selftest",
        "a11_review_id": "a11-review-selftest",
        "coordinator_slot": "selftest-slot",
    }
    library = manifest["library"]
    library["intended_library_path"] = "synthetic/a09-selftest/iTunes Library.itl"
    library["input"] = {"sha256": "0" * 64, "size_bytes": 4096, "mtime_ns": 1789084800000000000}
    if kind == "independent_writer_acceptance":
        library["expected_output"] = {"sha256": "1" * 64, "size_bytes": 8192}
    else:
        library["expected_output"] = {
            "sha256": None,
            "size_bytes": None,
            "unpredictable_reason": "native assigns identifiers and internal ordering keys",
            "capture_required": True,
        }
    for entry in manifest["media_inputs"]:
        entry["declared_location"] = "synthetic/a09-selftest/media/" + entry["filename"]
        entry["expected_native_title_source"] = (
            "filename" if entry["metadata_shape"] == "none" else "embedded tag"
        )
    for index, entry in enumerate(manifest["identities"]["entries"]):
        entry["old"] = {
            "present": False,
            "value": None,
            "absent_reason": "fresh synthetic library, no prior row",
        }
        if kind == "independent_writer_acceptance":
            entry["new"] = {"assignment": "declared", "value": "A09DECLARED%04d" % index}
    for phase in ("before", "after"):
        for row in manifest["locations"][phase]:
            row["path"] = "synthetic/a09-selftest/media/" + ROWS[row["fixture_id"]]["filename"]
    for playlist in manifest["playlists"]:
        playlist["order"] = list(reversed(playlist["membership"]))
        if kind == "independent_writer_acceptance":
            playlist["persistent_id"] = {"assignment": "declared", "value": "A09PLAYLIST0001"}
    return manifest


@pytest.mark.parametrize(
    "name", ["candidate-native-import-discovery.json", "candidate-independent-writer-acceptance.json"]
)
def test_committed_templates_are_structurally_valid_but_not_runnable(name):
    manifest = json.loads((EXPECTATIONS_DIR / name).read_text(encoding="utf-8"))
    assert manifest["schema"] == manifests.EXPECTATION_SCHEMA
    assert manifest["declaration_state"] == "template"
    assert manifest["operator"] == "a10"
    assert manifests.validate(manifest, registry=REGISTRY) == []
    runnable, problems = manifests.is_runnable(manifest, registry=REGISTRY)
    assert not runnable
    assert any("not declared" in problem for problem in problems)
    alignment = manifest["format_alignment"]
    assert alignment["format_owner"] == "a08"
    assert alignment["a08_format_published_at_authoring_time"] is False


@pytest.mark.parametrize("kind", list(manifests.CANDIDATE_KINDS))
def test_complete_declaration_is_runnable(kind):
    manifest = _complete_declaration(kind)
    runnable, problems = manifests.is_runnable(manifest, registry=REGISTRY)
    assert problems == []
    assert runnable


def _drop_identity(manifest):
    manifest["identities"]["entries"].pop()


def _clear_location(manifest):
    manifest["media_inputs"][0]["declared_location"] = None


def _forge_media_hash(manifest):
    manifest["media_inputs"][0]["sha256"] = "f" * 64


def _allow_protected_change(manifest):
    manifest["permitted_native_changes"]["allowed"].append("media_file_bytes")


def _drop_protected_field(manifest):
    manifest["permitted_native_changes"]["must_not_change"].remove("playlist_order")


def _prefill_observation(manifest):
    manifest["observations"]["library_output_sha256"] = "2" * 64


def _break_playlist_order(manifest):
    manifest["playlists"][0]["order"] = manifest["playlists"][0]["order"][:-1]


def _weaken_acceptance(manifest):
    manifest["acceptance"]["restart_cycles"] = 1
    manifest["acceptance"]["damaged_file_fallback_allowed"] = True


def _wrong_operator(manifest):
    manifest["operator"] = "a09"


def _drop_preflight(manifest):
    manifest["preflight"]["a08_review_id"] = None


def _predeclare_discovery_output(manifest):
    manifest["library"]["expected_output"]["sha256"] = "3" * 64


@pytest.mark.parametrize(
    "mutate,needle",
    [
        (_drop_identity, "identities is missing"),
        (_clear_location, "declared_location is required"),
        (_forge_media_hash, "the registry records"),
        (_allow_protected_change, "both allowed and protected"),
        (_drop_protected_field, "must_not_change is missing"),
        (_prefill_observation, "must stay empty until the run is executed"),
        (_break_playlist_order, "permutation of membership"),
        (_weaken_acceptance, "restart_cycles must be at least 2"),
        (_wrong_operator, "operator must be a10"),
        (_drop_preflight, "preflight.a08_review_id is required"),
        (_predeclare_discovery_output, "must not predeclare an output hash"),
    ],
)
def test_incomplete_declarations_are_rejected(mutate, needle):
    manifest = _complete_declaration()
    mutate(manifest)
    runnable, problems = manifests.is_runnable(manifest, registry=REGISTRY)
    assert not runnable
    assert any(needle in problem for problem in problems), problems


def test_writer_acceptance_must_declare_every_new_identifier():
    manifest = _complete_declaration("independent_writer_acceptance")
    entry = manifest["identities"]["entries"][0]
    entry["new"] = {
        "assignment": "native_assigned_to_observe",
        "value": None,
        "observation_slot": "observations.observed_identities",
    }
    runnable, problems = manifests.is_runnable(manifest, registry=REGISTRY)
    assert not runnable
    assert any("must declare every new id" in problem for problem in problems), problems


def test_writer_acceptance_must_predeclare_the_output_hash():
    manifest = _complete_declaration("independent_writer_acceptance")
    manifest["library"]["expected_output"] = {"sha256": None, "size_bytes": None}
    runnable, problems = manifests.is_runnable(manifest, registry=REGISTRY)
    assert not runnable
    assert any("predeclare library.expected_output.sha256" in problem for problem in problems), problems


def test_declared_media_must_match_the_reproducible_registry():
    manifest = _complete_declaration()
    original = copy.deepcopy(manifest)
    manifest["media_inputs"][0]["frames"] = original["media_inputs"][0]["frames"] + 1
    problems = manifests.validate(manifest, registry=REGISTRY)
    assert any("frames declared" in problem for problem in problems), problems
