from importlib.util import module_from_spec, spec_from_file_location
import hashlib
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


def load(name, path):
    spec = spec_from_file_location(name, path)
    module = module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


builder = load("delivery_builder_20260925", ROOT / "scripts/research/build_manifests.py")
verifier = load("delivery_verifier_20260925", ROOT / "scripts/research/verify_delivery.py")


def write_manifest(root, rows):
    (root / verifier.MANIFEST).write_text(json.dumps(rows), encoding="utf-8")


def row_for(root, relative):
    data = (root / relative).read_bytes()
    return {"path": relative, "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}


def test_builder_and_verifier_exclude_exact_generated_root_metadata(tmp_path, monkeypatch):
    (tmp_path / "sample.txt").write_text("tracked", encoding="utf-8")
    metadata = tmp_path / verifier.GENERATED_METADATA_DIR
    metadata.mkdir()
    (metadata / "PKG-INFO").write_text("generated", encoding="utf-8")
    monkeypatch.setattr(builder, "ROOT", tmp_path)
    rows = builder.build_delivery()
    assert [item["path"] for item in rows] == ["sample.txt"]
    write_manifest(tmp_path, rows)
    assert verifier.verify(tmp_path) == 1


def test_manifest_cannot_smuggle_generated_metadata_entry(tmp_path):
    (tmp_path / "sample.txt").write_text("tracked", encoding="utf-8")
    metadata = tmp_path / verifier.GENERATED_METADATA_DIR
    metadata.mkdir()
    (metadata / "PKG-INFO").write_text("generated", encoding="utf-8")
    write_manifest(
        tmp_path,
        [row_for(tmp_path, "sample.txt"), row_for(tmp_path, f"{verifier.GENERATED_METADATA_DIR}/PKG-INFO")],
    )
    with pytest.raises(ValueError, match="Excluded or self-referencing"):
        verifier.verify(tmp_path)


def test_exclusion_is_case_insensitive_for_cross_platform_replay(tmp_path, monkeypatch):
    (tmp_path / "sample.txt").write_text("tracked", encoding="utf-8")
    metadata = tmp_path / verifier.GENERATED_METADATA_DIR.upper()
    metadata.mkdir()
    (metadata / "PKG-INFO").write_text("generated", encoding="utf-8")
    monkeypatch.setattr(builder, "ROOT", tmp_path)
    assert [item["path"] for item in builder.build_delivery()] == ["sample.txt"]


def test_other_egg_info_directory_remains_in_exact_file_set(tmp_path, monkeypatch):
    metadata = tmp_path / "other.egg-info"
    metadata.mkdir()
    (metadata / "PKG-INFO").write_text("not generated by this project", encoding="utf-8")
    monkeypatch.setattr(builder, "ROOT", tmp_path)
    rows = builder.build_delivery()
    assert [item["path"] for item in rows] == ["other.egg-info/PKG-INFO"]
    write_manifest(tmp_path, rows)
    assert verifier.verify(tmp_path) == 1


def test_nested_same_name_directory_remains_in_exact_file_set(tmp_path, monkeypatch):
    metadata = tmp_path / "nested" / verifier.GENERATED_METADATA_DIR
    metadata.mkdir(parents=True)
    (metadata / "PKG-INFO").write_text("nested content", encoding="utf-8")
    monkeypatch.setattr(builder, "ROOT", tmp_path)
    rows = builder.build_delivery()
    assert [item["path"] for item in rows] == [f"nested/{verifier.GENERATED_METADATA_DIR}/PKG-INFO"]
    write_manifest(tmp_path, rows)
    assert verifier.verify(tmp_path) == 1


def test_builder_excludes_git_pointer_file_in_linked_worktree(tmp_path, monkeypatch):
    (tmp_path / ".git").write_text("gitdir: elsewhere", encoding="utf-8")
    (tmp_path / "sample.txt").write_text("tracked", encoding="utf-8")
    monkeypatch.setattr(builder, "ROOT", tmp_path)
    assert [item["path"] for item in builder.build_delivery()] == ["sample.txt"]
